### ISSUE TITLE
Homu checks if setting a label is allowed before checking if it exists

### ISSUE THREAD

**Issue by jyn514** [rust-lang/homu#130]
Labels are public, so there's no point to this, and it makes the errors harder to read.

_Originally posted by @rustbot in https://github.com/rust-lang/rust/issues/76447#issuecomment-740565685_

**Comment by jyn514** [comment]
Err I think this should have been filed on https://github.com/rust-lang/triagebot/ instead.

**Comment by camelid** [comment]
@jyn514 Could you close this issue and open it on rust-lang/triagebot instead?
