### ISSUE TITLE
bors squash left commit separate from PR/rollup in gh history

### ISSUE THREAD

**Issue by klensy** [rust-lang/homu#182]
PR: https://github.com/rust-lang/rust/pull/101806

And now check github history: https://github.com/rust-lang/rust/commits?author=bors for `Sep 20, 2022`, there separate non PR/rollup commit.

`squash` bors command should be disabled: it used rarely, and if used, it sometimes(often?) works not in way as it expected.

**Comment by klensy** [comment]
And that PR affected by #181 too.

**Comment by jyn514** [comment]
Duplicate of https://github.com/rust-lang/homu/issues/181
