### ISSUE TITLE
can't unapprove my own PRs

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/homu#40]
People need to be able to `r-` their own PRs.

Use case:

I make a PR that updates clippy.
The PR is `r+`ed and prioritized.
In the meantime another rollup merges and breaks clippy again.
Now the clippy-pr needs to be updated again to a working version of clippy since it won't pass CI otherwise but I cannot prevent it from being tested and potentially waste 3 hours of CI time since I cannot `r-` PRs I authored.

https://github.com/rust-lang/rust/pull/61298#issuecomment-496822167

**Comment by kennytm** [comment]
Note that you could workaround by close-and-reopen or push a new commit.
