### ISSUE TITLE
Add `@bors perf` command or similar

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/homu#62]
The typical workflow when having to get perf data for a commit is
```
@bors try
```
(wait until bors posts that it is done)
```
@rust-timer build SHA
```
(wait until that is done)

It would be great if bors would have a command like `perf`, that would work basically exactly the same as `try`, except that the "try build done" message would invoke the rust-timer bot the same way that we currently have to do manually (yay, bots calling bots). So, no human interaction should be needed, after doing `@bors perf`, until the final perf results are in.

Cc @Mark-Simulacrum

**Comment by bryanburgers** [comment]
Would this be appropriate for all repos that bors handles, or just rust-lang/rust?

**Comment by RalfJung** [comment]
Only repos that have `@rust-timer`, so likely only rust-lang/rust.

**Comment by pietroalbini** [comment]
It would probably be better to add this to rust-timer itself?

**Comment by Mark-Simulacrum** [comment]
Yeah, I think historically I've thought about this as rust-timer invoking bors try as appropriate; I would accept a PR doing so for rustc-perf.

**Comment by RalfJung** [comment]
@Mark-Simulacrum how would the interaction look like? I would do `@rust-timer <verb>`, and then that bot would do `@bors try`, and remember to check new comments added by bors that say that a try built is done, and when such a comment comes in, it acts as if `@rust-timer build <sha>` had been written?

**Comment by Mark-Simulacrum** [comment]
That's what I'd imagine, yes.

**Comment by Centril** [comment]
Update: We now have `@bors try @rust-timer queue`.

**Comment by Mark-Simulacrum** [comment]
I don't think we can do better than that personally (or should, perhaps). So closing.
