### ISSUE TITLE
bors commands in review comments do not trigger any actions

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/homu#66]
Reviewing a PR with an approve comment and writing "@bors: r+" in it does not trigger any actions. See: https://github.com/rust-lang/libc/pull/1526#issuecomment-534449452

**Comment by Mark-Simulacrum** [comment]
GitHub requires entirely separate handling of the body of approve comments and I objected to the amount of additional code that would be required to support this. Closing as won't fix.
