### ISSUE TITLE
Two different PR's shown with supposedly the same PR number

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/homu#72]
![image](https://user-images.githubusercontent.com/17426603/66514977-7babb280-eade-11e9-9cd8-3b068e4c650c.png)

**Comment by mati865** [comment]
Sometimes PRs on the dashboard have wrong number, it's fixed after somebody from infra clicks "Synchronize" button.

**Comment by pietroalbini** [comment]
I think this was caused by the rollup changes @centril made, and I rolled them back a few minutes ago. Closing this for now, please reopen it if y'all see this again.
