### ISSUE TITLE
Refuse to create rollups with unapproved PRs

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/homu#80]
Currently, it is fairly easy to accidentally create a rollup containing an unapproved PR: all it takes is a wrong click in the long column of checkboxes on the left.

Would it be possible to disable/remove those checkboxes for PRs that are not actually enqueued, or else at least warn before creating a rollup that contains an unapproved PR?

**Comment by RalfJung** [comment]
Cc @pietroalbini 

This same mechanism could also refuse to rollup PRs with rollup=never

**Comment by pietroalbini** [comment]
To implement this, [change the table rendering code](https://github.com/rust-lang/homu/blob/0fd6fd6851e92b8191c4ce2b57761c5f4c2a4e8e/homu/html/queue.html#L167-L188) to show the checkbox only if the status is `approved`. If you have any questions feel free to ping me or [ask on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra)!
