### ISSUE TITLE
Support for easier re-rollups

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/homu#89]
Re-rollups (rolling up with a very similar set of PRs, because one of them failed or so) are currently quite painful. It would be great to get better support from bors for that.

@pietroalbini had a great idea for this that does not require extra server-side state:
> add a "Create a similar rollup" link in the rollup PR body, with the link going to https://bors.rust-lang.org/queue/rust?prs=12345,6583,342345

**Comment by pietroalbini** [comment]
To implement this, two changes are needed:

* [When the PR message is generated](https://github.com/rust-lang/homu/blob/0fd6fd6851e92b8191c4ce2b57761c5f4c2a4e8e/homu/server.py#L325-L331) include an URL to the queue page with the list of PRs included in the rollup in the query string. You'll need to gather the current base URL for that (you can add a field in the configuration for it).
* [In the queue page](https://github.com/rust-lang/homu/blob/0fd6fd6851e92b8191c4ce2b57761c5f4c2a4e8e/homu/server.py#L111) extract the list of PRs from the query string (if present), and pass it to the template. [In the template](https://github.com/rust-lang/homu/blob/0fd6fd6851e92b8191c4ce2b57761c5f4c2a4e8e/homu/html/queue.html#L169) check the checkbox if the PR is in the list.

If you have any questions feel free to ping me or [ask on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra)!

**Comment by Manishearth** [comment]
An important thing to note is that the JS should only check the checkbox for PRs which are approved or not-try pending

**Comment by oliviacrain** [comment]
It looks like no one has taken this up- I'll take a crack at this tonight!
