### ISSUE TITLE
Refuse to create rollups with rollup=never

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/homu#91]
This is very similar to https://github.com/rust-lang/homu/issues/80: just like unapproved PRs should not be in a rollup, the same goes for "rollup=never" PRs. So maybe it would make sense to likewise block them?

Cc @pietroalbini

**Comment by pietroalbini** [comment]
Yeah it makes sense. I'm happy to review PRs for it!

**Comment by Manishearth** [comment]
Heh, i just wanted to file this issue as well
